spring:
  datasource:
    druid:  # druid连接池配置
      url: jdbc:mysql://192.168.23.49:3306/tg?characterEncoding=utf-8&useSSL=false  # 数据库URL
      username: root  # 数据库用户名
      password: $Abc123456  # 数据库密码
      driverClassName: com.mysql.jdbc.Driver  # 数据库驱动类
      maxActive: 30  # 最大连接数
      minIdle: 5  # 最小保持的连接数
      maxWait: 10000  # 获取连接的最大等待时间
      validationQuery: 'SELECT 1'  # 解决Mysql8小时的问题，验证连接是否有效
      timeBetweenEvictionRunsMillis: 60000  # 空闲连接检查的时间间隔
      minEvictableIdleTimeMillis: 300000  # 空闲连接最小空闲时间
  jackson:  # Jackson序列化配置
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:  # 日志配置
  level:
    com.gedoumi.tg.component.RequestInterceptor: info