spring:
  datasource:
    druid:  # druid连接池配置
      url: jdbc:mysql://localhost:3306/crowd?characterEncoding=utf-8&useSSL=false  # 数据库URL
      username: root  # 数据库用户名
      password: root  # 数据库密码
      driverClassName: com.mysql.jdbc.Driver  # 数据库驱动类
      maxActive: 30  # 最大连接数
      minIdle: 5  # 最小保持的连接数
      maxWait: 10000  # 获取连接的最大等待时间
      validationQuery: 'SELECT 1'  # 解决Mysql8小时的问题，验证连接是否有效
      timeBetweenEvictionRunsMillis: 60000  # 空闲连接检查的时间间隔
      minEvictableIdleTimeMillis: 300000  # 空闲连接最小空闲时间
  jackson:  # Jackson序列化配置
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  freemarker:  # Freemarker配置
    charset: UTF-8
    content-type: text/html;charset=UTF-8
#    suffix: .html
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
      auto_import: common.ftl as common  # 设置包文件以及别名

mybatis:  # MyBatis配置项
  type-aliases-package: com.gedoumi.crowd  # 别名包
  mapper-locations: classpath:/mappers/*.xml  # xml文件位置
  configuration:
    cache-enabled: false  # 关闭缓存
    map-underscore-to-camel-case: true  # 是否开启自动驼峰命名规则
    use-generated-keys: true  # 自动生成主键
    default-executor-type: reuse  # 配置默认的执行器（REUSE 执行器会重用预处理语句）
    default-statement-timeout: 600  # 事务超时时间

pagehelper:  # MyBatis分页插件配置项
  helperDialect: mysql
  #  reasonable: true  # 分页合理性
  support-methods-arguments: true
  params: count=countSql

logging:  # 日志配置
  level:
    com.gedoumi.tg.component.RequestInterceptor: info
    com.gedoumi.tg.component.WebSocketHandler: debug
    com.gedoumi.tg.service.AwardService: debug  # 抽奖